# ymlのバージョン
version: '3'

# コンテナサービスを指定
services:
    # sample(任意の名前)のサービスを作成
    sample :
        # 同一フォルダにある Dockerfile をビルドする
        build: ./
        # 外部と接続する(外部ポート:dockerポート)
        ports:
            - "8080:8080"
        # コンテナ名を指定(任意の名前)
        container_name: sample_WebApp
        # コンテナが起動し続ける
        tty: true
        # ホストのディレクトリをコンテナにマウント
        volumes:
          - C:\Docker\sample\:/go/src/github.com/sample